FROM continuumio/miniconda3:4.6.14

ENV TERM linux
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y

ENV LANG en_US.UTF-8

COPY ./environment.yml .

RUN conda config --set channel_priority true \
    && conda env create -f environment.yml \
    && rm -rf /opt/conda/pkgs/*
ENV PATH /opt/conda/envs/dagster/bin:$PATH

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME
ADD . /opt/dagster/app/
COPY .env /opt/dagster/app/
COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR /opt/dagster/app

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "repo.py"]