name: dagster
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.3.29
  - freetds=1.3.3
  - krb5=1.19.2
  - libedit=3.*
  - libopenblas=0.3.*
  - ncurses=6.3
  - numpy-base=1.21.2
  - openssl=1.1.1n
  - pysocks
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytz=2021.3
  - readline=8.1.2
  - six=1.16.0
  - sqlite=3.38.2
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alembic==1.6.5
    - aniso8601==7.0.0
    - anyio==3.5.0
    - asgiref==3.5.0
    - attrs==21.4.0
    - bleach==5.0.0
    - boto3
    - bottleneck==1.*
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.12
    - click==8.1.2
    - coloredlogs==14.0
    - croniter==1.3.4
    - dagit==0.14.7
    - dagster==0.14.7
    - dagster-aws==0.14.7
    - dagster-docker==0.14.7
    - dagster-graphql==0.14.7
    - dagster-postgres==0.14.7
    - defusedxml==0.7.1
    - docstring-parser==0.13
    - entrypoints==0.4
    - gevent==21.12.0
    - gevent-websocket==0.10.1
    - GoogleNews
    - google-auth==2.6.3
    - google-auth-oauthlib==0.5.1
    - gql==2.0.0
    - graphene==2.1.9
    - graphql-core==2.3.2
    - graphql-relay==2.0.1
    - greenlet==1.1.2
    - grpcio==1.44.0
    - grpcio-health-checking==1.43.0
    - gspread==5.3.0
    - gspread-dataframe==3.3.0
    - h11==0.13.0
    - httptools==0.4.0
    - humanfriendly==10.0
    - idna==3.3
    - ipython-genutils==0.2.0
    - jinja2==2.11.3
    - joblib
    - jsonschema==4.4.0
    - jupyter-core==4.9.2
    - mako==1.2.0
    - markupsafe==2.0.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.1.3
    - numexpr==2.8.1
    - numpy==1.21.2
    - oauthlib==3.2.0
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - pendulum==2.1.2
    - pep562==1.1
    - pillow==9.2.0
    - pip==21.2.4
    - promise==2.3
    - protobuf==3.20.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.11.2
    - pymssql==2.*
    - pymongo==4.0.2
    - pyrsistent==0.18.1
    - python-dotenv
    - python-editor==1.0.4
    - pytzdata==2020.1
    - pyyaml==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - rx==1.6.1
    - scikit-learn
    - scipy
    - setuptools==58.0.4
    - slack-sdk
    - sniffio==1.2.0
    - sqlalchemy==1.4.35
    - starlette==0.19.0
    - stem
    - tabulate==0.8.9
    - testpath==0.6.0
    - toposort==1.7
    - tqdm==4.64.0
    - traitlets==5.1.1
    - tweepy
    - typing-compat==0.1.0
    - urllib3==1.26.9
    - uvicorn==0.17.6
    - uvloop==0.16.0
    - watchdog==2.1.7
    - watchgod==0.8.2
    - webencodings==0.5.1
    - websockets==10.2
    - zope-event==4.5.0
    - zope-interface==5.4.0
